#conexion a la base de datos con el usuario root y su contrasena.
spring.application.name=login
spring.datasource.url=jdbc:mysql://localhost:3306/db_estacion
spring.datasource.username=root
spring.datasource.password=040585

#configuracion del JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081